### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by laszlo-major** [Frende/Frende.AccessTokenTool#1]
Thanks for the tool, it's always nice to get a clear idea what exactly needs to be done. One small note is that while the script is valid on macos, the built-in 'date' does not work with these parameters. 
The simplest workaround is [brew] install coreutils, and change the script to refer to 'gdate' instead of 'date' on macos. Just FYI if you want to add it in the readme.

**Comment by Hakon** [comment]
Hi.
This should be fixed in 7e7295c186ecf8906d1e5e4fc185223384d8bab6 by using perl instead.
Give it a try 🙂

**Comment by laszlo-major** [comment]
Works like a charm, cheers.
